# Configuration for the audio and LLM processing pipeline

paths:
  audio_dir: /kaggle/input/up366-audio/audio   # Input audio sets directory
  output_dir: ./output                # Main output directory for text files
  temp_dir: ./temp                    # Temporary directory for intermediate files
  nemo_yaml: diar_infer_general.yaml  # NeMo diarization config

processing:
  clean_temp: true                    # Clean up temp files after processing each set

audio_processing:
  gender_model: alefiury/wav2vec2-large-xlsr-53-gender-recognition-librispeech
  whisper_model: small.en

